name: unit tests

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

jobs:
  setup:
    name: Bootstrap and create matrix
    runs-on: ubuntu-latest
    outputs:
      veracity-matrix: ${{ steps.veracity-bootstrap.outputs.veracity-matrix }}
    steps:
      - name: Checkout CI repo
        uses: actions/checkout@v4

      - name: "veracity: bootstrap & create matrix"
        id: veracity-bootstrap
        run: |
          # Target dir to clone into
          export TARGET_DIR="veracity"

          # Download and execute the bootstrap script
          GIT_BOOTSTRAP_SH=$(curl -fsSL https://raw.githubusercontent.com/robinbryce/git-bootstrap/refs/heads/main/git-bootstrap.sh)
          dirs=$(sh -c "$GIT_BOOTSTRAP_SH" - dirs "$TARGET_DIR")
          sh -c "$GIT_BOOTSTRAP_SH" - clone "$TARGET_DIR" --depth 1
          sh -c "$GIT_BOOTSTRAP_SH" - checkout "$TARGET_DIR"

          # Collect list of cloned repo directories (assumes one subdir per repo)
          repo_list=$(for repo in $dirs; do echo "\"$repo\""; done | paste -sd, -)
          echo "veracity-matrix={\"repo\":[${repo_list}]}" >> $GITHUB_OUTPUT

      - name: "veracity: upload clones artifact"
        id: veracity-clones-artifact-upload
        uses: actions/upload-artifact@v4
        with:
          name: veracity-shallow-clones
          path: veracity/

  veracity-unit-test:
    name: "veracity: unit tests"
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.veracity-matrix) }}
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - name: "veracity: download shallow clones artifact"
        uses: actions/download-artifact@v4
        id: veracity-clones-artifact-download
        with:
          name: veracity-shallow-clones
          path: veracity/

      - name: "cache go module downloads"
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-${{ runner.os }}-

      - name: "unit test: ${{ matrix.repo }}"
        run: |
          cd veracity/${{ matrix.repo }}
          find . -name go.mod -execdir sh -c 'echo "Running tests in $(pwd)"; go test ./...' \;
